[package]
name = "shellcast"
version = "0.1.0"
edition = "2024"

[dependencies]
atom_syndication = "0.12.7"
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.29.0"
reqwest = { version = "0.12.24", features = ["blocking"] }
rss = { version = "2.0.12", features = ["atom"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
